# @package _global_

# specify here default training configuration
defaults:
  - _self_
  - detector: yolov5.yaml
  - model: regressor.yaml
  - augmentation: inference_preprocessing.yaml

  # debugging config (enable through command line, e.g. `python train.py debug=default)
  - debug: null

  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

# run name
name: evaluate

# directory
root: ${hydra:runtime.cwd}

# predictions/output directory
# pred_dir: ${root}/${hydra:run.dir}/${name}

# for exist predicitions directory
pred_dir: ${root}/outputs/2022-09-29/09-42-21/evaluate

# calib_file
calib_file: ${root}/data/global_calib.txt

# regressor weights
regressor_weights: ${root}/weights/mobilenetv3-best.pt

# validation images directory
val_images_path: ${root}/data/KITTI/images

# validation sets directory
val_sets: ${root}/data/KITTI/val_80.txt

# class to evaluated
classes: 2

# class_to_name = {
#     0: 'Car',
#     1: 'Pedestrian',
#     2: 'Cyclist',
#     3: 'Van',
#     4: 'Person_sitting',
#     5: 'car',
#     6: 'tractor',
#     7: 'trailer',
# }

# gt/label path
gt_dir: ${root}/data/KITTI/label_2

# device to inference
device: 'cuda:0'